Diet.create!([
  {name: "Lactose Intolerance"},
  {name: "Vegetarian"},
  {name: "Peanut Allergy"},
  {name: "Diabetic"},
  {name: "Gluten Free"},
  {name: "Kosher"}
])
DietFood.create!([
  {food_id: "Potato_Chips", diet_id: "Gluten_Free"},
  {food_id: "Potato_Chips", diet_id: "Lactose_Intolerance"},
  {food_id: "Potato_Chips", diet_id: "Vegetarian"},
  {food_id: "Potato_Chips", diet_id: "Peanut_Allergy"},
  {food_id: "Potato_Chips", diet_id: "Gluten_Free"},
  {food_id: "Potato_Chips", diet_id: "Kosher"},
  {food_id: nil, diet_id: "Lactose_Intolerance"},
  {food_id: nil, diet_id: "Vegetarian"},
  {food_id: nil, diet_id: "Peanut_Allergy"},
  {food_id: nil, diet_id: "Kosher"},
  {food_id: "Pasta", diet_id: "Lactose_Intolerance"},
  {food_id: "Pasta", diet_id: "Vegetarian"},
  {food_id: "Pasta", diet_id: "Peanut_Allergy"},
  {food_id: "Pasta", diet_id: "Kosher"},
  {food_id: "Vanilla_Ice_Cream", diet_id: "Vegetarian"},
  {food_id: "Vanilla_Ice_Cream", diet_id: "Peanut_Allergy"},
  {food_id: "Vanilla_Ice_Cream", diet_id: "Gluten_Free"},
  {food_id: "Vanilla_Ice_Cream", diet_id: "Kosher"},
  {food_id: "Chocolate_Cookies", diet_id: "Vegetarian"},
  {food_id: "Chocolate_Cookies", diet_id: "Kosher"},
  {food_id: "Kale_Chips", diet_id: "Lactose_Intolerance"},
  {food_id: "Kale_Chips", diet_id: "Vegetarian"},
  {food_id: "Kale_Chips", diet_id: "Peanut_Allergy"},
  {food_id: "Kale_Chips", diet_id: "Diabetic"},
  {food_id: "Kale_Chips", diet_id: "Gluten_Free"},
  {food_id: "Kale_Chips", diet_id: "Kosher"},
  {food_id: "Zucchini_Chips", diet_id: "Lactose_Intolerance"},
  {food_id: "Zucchini_Chips", diet_id: "Vegetarian"},
  {food_id: "Zucchini_Chips", diet_id: "Peanut_Allergy"},
  {food_id: "Zucchini_Chips", diet_id: "Diabetic"},
  {food_id: "Zucchini_Chips", diet_id: "Gluten_Free"},
  {food_id: "Zucchini_Chips", diet_id: "Kosher"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Lactose_Intolerance"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Vegetarian"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Peanut_Allergy"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Gluten_Free"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Kosher"},
  {food_id: "Sweet_Potato_Chips", diet_id: "Diabetic"},
  {food_id: "Baked_Beet_Chips", diet_id: "Lactose_Intolerance"},
  {food_id: "Baked_Beet_Chips", diet_id: "Vegetarian"},
  {food_id: "Baked_Beet_Chips", diet_id: "Peanut_Allergy"},
  {food_id: "Baked_Beet_Chips", diet_id: "Diabetic"},
  {food_id: "Baked_Beet_Chips", diet_id: "Gluten_Free"},
  {food_id: "Baked_Beet_Chips", diet_id: "Kosher"},
  {food_id: "Oatmeal_Cookies", diet_id: "Lactose_Intolerance"},
  {food_id: "Oatmeal_Cookies", diet_id: "Vegetarian"},
  {food_id: "Oatmeal_Cookies", diet_id: "Kosher"},
  {food_id: "Almond_Cookies", diet_id: "Lactose_Intolerance"},
  {food_id: "Almond_Cookies", diet_id: "Vegetarian"},
  {food_id: "Almond_Cookies", diet_id: "Peanut_Allergy"},
  {food_id: "Almond_Cookies", diet_id: "Kosher"},
  {food_id: "Buckwheat_Cookies", diet_id: "Lactose_Intolerance"},
  {food_id: "Buckwheat_Cookies", diet_id: "Vegetarian"},
  {food_id: "Buckwheat_Cookies", diet_id: "Peanut_Allergy"},
  {food_id: "Buckwheat_Cookies", diet_id: "Gluten_Free"},
  {food_id: "Buckwheat_Cookies", diet_id: "Kosher"},
  {food_id: "Granola_Cookies", diet_id: "Lactose_Intolerance"},
  {food_id: "Granola_Cookies", diet_id: "Vegetarian"},
  {food_id: "Granola_Cookies", diet_id: "Peanut_Allergy"},
  {food_id: "Granola_Cookies", diet_id: "Kosher"},
  {food_id: "Chickpea_Pasta", diet_id: "Lactose_Intolerance"},
  {food_id: "Chickpea_Pasta", diet_id: "Vegetarian"},
  {food_id: "Chickpea_Pasta", diet_id: "Peanut_Allergy"},
  {food_id: "Chickpea_Pasta", diet_id: "Diabetic"},
  {food_id: "Chickpea_Pasta", diet_id: "Gluten_Free"},
  {food_id: "Chickpea_Pasta", diet_id: "Kosher"},
  {food_id: "Quinoa_Pasta", diet_id: "Lactose_Intolerance"},
  {food_id: "Quinoa_Pasta", diet_id: "Vegetarian"},
  {food_id: "Quinoa_Pasta", diet_id: "Peanut_Allergy"},
  {food_id: "Quinoa_Pasta", diet_id: "Diabetic"},
  {food_id: "Quinoa_Pasta", diet_id: "Gluten_Free"},
  {food_id: "Quinoa_Pasta", diet_id: "Kosher"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Lactose_Intolerance"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Diabetic"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Vegetarian"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Peanut_Allergy"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Gluten_Free"},
  {food_id: "Brown_Rice_Pasta", diet_id: "Kosher"},
  {food_id: "Corn_Pasta", diet_id: "Lactose_Intolerance"},
  {food_id: "Corn_Pasta", diet_id: "Vegetarian"},
  {food_id: "Corn_Pasta", diet_id: "Peanut_Allergy"},
  {food_id: "Corn_Pasta", diet_id: "Diabetic"},
  {food_id: "Corn_Pasta", diet_id: "Gluten_Free"},
  {food_id: "Corn_Pasta", diet_id: "Kosher"},
  {food_id: "Non_Fat_Frozen_Yogurt", diet_id: "Vegetarian"},
  {food_id: "Non_Fat_Frozen_Yogurt", diet_id: "Gluten_Free"},
  {food_id: "Non_Fat_Frozen_Yogurt", diet_id: "Peanut_Allergy"},
  {food_id: "Non_Fat_Frozen_Yogurt", diet_id: "Kosher"},
  {food_id: "Frozen_Bananas", diet_id: "Lactose_Intolerance"},
  {food_id: "Frozen_Bananas", diet_id: "Vegetarian"},
  {food_id: "Frozen_Bananas", diet_id: "Peanut_Allergy"},
  {food_id: "Frozen_Bananas", diet_id: "Diabetic"},
  {food_id: "Frozen_Bananas", diet_id: "Gluten_Free"},
  {food_id: "Frozen_Bananas", diet_id: "Kosher"},
  {food_id: "Coconut_Granita", diet_id: "Lactose_Intolerance"},
  {food_id: "Coconut_Granita", diet_id: "Vegetarian"},
  {food_id: "Coconut_Granita", diet_id: "Peanut_Allergy"},
  {food_id: "Coconut_Granita", diet_id: "Gluten_Free"},
  {food_id: "Coconut_Granita", diet_id: "Kosher"},
  {food_id: "Almond_Milk_Popsicle", diet_id: "Lactose_Intolerance"},
  {food_id: "Almond_Milk_Popsicle", diet_id: "Vegetarian"},
  {food_id: "Almond_Milk_Popsicle", diet_id: "Peanut_Allergy"},
  {food_id: "Almond_Milk_Popsicle", diet_id: "Gluten_Free"},
  {food_id: "Almond_Milk_Popsicle", diet_id: "Kosher"},
  {food_id: "Carrot_Cake", diet_id: "Lactose_Intolerance"},
  {food_id: "Carrot_Cake", diet_id: "Vegetarian"},
  {food_id: "Carrot_Cake", diet_id: "Peanut_Allergy"},
  {food_id: "Carrot_Cake", diet_id: "Kosher"},
  {food_id: "Lemon_Cake", diet_id: "Lactose_Intolerance"},
  {food_id: "Lemon_Cake", diet_id: "Vegetarian"},
  {food_id: "Lemon_Cake", diet_id: "Peanut_Allergy"},
  {food_id: "Lemon_Cake", diet_id: "Kosher"},
  {food_id: "Pumpkin_Cake", diet_id: "Lactose_Intolerance"},
  {food_id: "Pumpkin_Cake", diet_id: "Vegetarian"},
  {food_id: "Pumpkin_Cake", diet_id: "Peanut_Allergy"},
  {food_id: "Pumpkin_Cake", diet_id: "Kosher"},
  {food_id: "Banana_Cake", diet_id: "Gluten_Free"},
  {food_id: "Banana_Cake", diet_id: "Lactose_Intolerance"},
  {food_id: "Banana_Cake", diet_id: "Vegetarian"},
  {food_id: "Banana_Cake", diet_id: "Peanut_Allergy"},
  {food_id: "Banana_Cake", diet_id: "Kosher"}
])
Food.create!([
  {name: "Potato Chips", stars: 2, energy: 150, fat: "0.1", saturated_fat: "3.2", sugar: "3.7", sodium: 311, default_filter: "SaltSwitch"},
  {name: "Chocolate Cookies", stars: 3, energy: 171, fat: "4.0", saturated_fat: "2.4", sugar: "10.8", sodium: 153, default_filter: "SugarSwitch"},
  {name: "Pasta", stars: 2, energy: 208, fat: "7.7", saturated_fat: "3.0", sugar: "4.9", sodium: 650, default_filter: "GlutenSwitch"},
  {name: "Vanilla Ice Cream", stars: 1, energy: 192, fat: "15.2", saturated_fat: "2.8", sugar: "18.0", sodium: 170, default_filter: "FatSwitch"},
  {name: "Chocolate Cake", stars: 1, energy: 285, fat: "13.8", saturated_fat: "5.4", sugar: "27.0", sodium: 241, default_filter: "EnergySwitch"},
  {name: "Kale Chips", stars: 5, energy: 80, fat: "8.0", saturated_fat: "1.0", sugar: "0.0", sodium: 75, default_filter: "SaltSwitch"},
  {name: "Zucchini Chips", stars: 5, energy: 75, fat: "7.0", saturated_fat: "1.0", sugar: "0.0", sodium: 85, default_filter: "SaltSwitch"},
  {name: "Sweet Potato Chips", stars: 5, energy: 75, fat: "11.0", saturated_fat: "7.0", sugar: "2.0", sodium: 120, default_filter: "SaltSwitch"},
  {name: "Baked Beet Chips", stars: 5, energy: 85, fat: "5.0", saturated_fat: "0.5", sugar: "150.0", sodium: 130, default_filter: "SaltSwitch"},
  {name: "Oatmeal Cookies", stars: 5, energy: 72, fat: "3.5", saturated_fat: "0.6", sugar: "4.0", sodium: 29, default_filter: "SugarSwitch"},
  {name: "Almond Cookies", stars: 5, energy: 75, fat: "5.0", saturated_fat: "0.6", sugar: "6.0", sodium: 50, default_filter: "SugarSwitch"},
  {name: "Buckwheat Cookies", stars: 5, energy: 100, fat: "3.9", saturated_fat: "0.6", sugar: "9.0", sodium: 90, default_filter: "SugarSwitch"},
  {name: "Granola Cookies", stars: 5, energy: 140, fat: "3.5", saturated_fat: "0.6", sugar: "11.0", sodium: 60, default_filter: "SugarSwitch"},
  {name: "Chickpea Pasta", stars: 5, energy: 190, fat: "3.5", saturated_fat: "0.4", sugar: "0.0", sodium: 0, default_filter: "GlutenSwitch"},
  {name: "Quinoa Pasta", stars: 5, energy: 170, fat: "2.5", saturated_fat: "0.0", sugar: "1.0", sodium: 0, default_filter: "GlutenSwitch"},
  {name: "Brown Rice Pasta", stars: 5, energy: 120, fat: "2.5", saturated_fat: "0.0", sugar: "1.0", sodium: 15, default_filter: "GlutenSwitch"},
  {name: "Corn Pasta", stars: 4, energy: 320, fat: "2.5", saturated_fat: "0.0", sugar: "1.0", sodium: 12, default_filter: "GlutenSwitch"},
  {name: "Non Fat Frozen Yogurt", stars: 5, energy: 110, fat: "0.0", saturated_fat: "0.0", sugar: "0.0", sodium: 0, default_filter: "FatSwitch"},
  {name: "Frozen Bananas", stars: 5, energy: 105, fat: "0.0", saturated_fat: "0.0", sugar: "14.0", sodium: 0, default_filter: "FatSwitch"},
  {name: "Coconut Granita", stars: 4, energy: 80, fat: "0.0", saturated_fat: "0.0", sugar: "20.0", sodium: 0, default_filter: "FatSwitch"},
  {name: "Almond Milk Popsicle", stars: 5, energy: 110, fat: "5.0", saturated_fat: "1.5", sugar: "14.0", sodium: 153, default_filter: "FatSwitch"},
  {name: "Carrot Cake", stars: 5, energy: 180, fat: "4.2", saturated_fat: "2.5", sugar: "9.4", sodium: 324, default_filter: "EnergySwitch"},
  {name: "Lemon Cake", stars: 5, energy: 91, fat: "3.1", saturated_fat: "0.4", sugar: "5.0", sodium: 210, default_filter: "EnergySwitch"},
  {name: "Pumpkin Cake", stars: 4, energy: 188, fat: "3.1", saturated_fat: "1.8", sugar: "125.0", sodium: 320, default_filter: "EnergySwitch"},
  {name: "Banana Cake", stars: 5, energy: 160, fat: "2.5", saturated_fat: "1.1", sugar: "1.0", sodium: 85, default_filter: "EnergySwitch"}
])
Suggestion.create!([
  {original_food_id: "Potato_Chips", health_suggestion_id: "Zucchini_Chips", filter: "SaltSwitch"},
  {original_food_id: "Potato_Chips", health_suggestion_id: "Sweet_Potato_Chips", filter: "SaltSwitch"},
  {original_food_id: "Potato_Chips", health_suggestion_id: "Baked_Beet_Chips", filter: "SaltSwitch"},
  {original_food_id: nil, health_suggestion_id: "Oatmeal_Cookies", filter: "SugarSwitch"},
  {original_food_id: "Potato_Chips", health_suggestion_id: "Kale_Chips", filter: "SaltSwitch"},
  {original_food_id: nil, health_suggestion_id: "Almond_Cookies", filter: "SugarSwitch"},
  {original_food_id: nil, health_suggestion_id: "Buckwheat_Cookies", filter: "SugarSwitch"},
  {original_food_id: nil, health_suggestion_id: "Granola_Cookies", filter: "SugarSwitch"},
  {original_food_id: "Pasta", health_suggestion_id: "Chickpea_Pasta", filter: "GlutenSwitch"},
  {original_food_id: "Pasta", health_suggestion_id: "Quinoa_Pasta", filter: "GlutenSwitch"},
  {original_food_id: "Pasta", health_suggestion_id: "Brown_Rice_Pasta", filter: "GlutenSwitch"},
  {original_food_id: "Pasta", health_suggestion_id: "Corn_Pasta", filter: "GlutenSwitch"},
  {original_food_id: "Vanilla_Ice_Cream", health_suggestion_id: "Non_Fat_Frozen_Yogurt", filter: "FatSwitch"},
  {original_food_id: "Vanilla_Ice_Cream", health_suggestion_id: "Frozen_Bananas", filter: "FatSwitch"},
  {original_food_id: "Vanilla_Ice_Cream", health_suggestion_id: "Coconut_Granita", filter: "FatSwitch"},
  {original_food_id: "Vanilla_Ice_Cream", health_suggestion_id: "Almond_Milk_Popsicle", filter: "FatSwitch"},
  {original_food_id: "Chocolate_Cookies", health_suggestion_id: "Carrot_Cake", filter: "EnergySwitch"},
  {original_food_id: "Chocolate_Cookies", health_suggestion_id: "Lemon_Cake", filter: "EnergySwitch"},
  {original_food_id: "Chocolate_Cookies", health_suggestion_id: "Pumpkin_Cake", filter: "EnergySwitch"},
  {original_food_id: "Chocolate_Cookies", health_suggestion_id: "Banana_Cake", filter: "EnergySwitch"}
])
